# Generated by Django 5.0.6 on 2024-05-25 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appModelosDB', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriaproducto',
            name='nombre_categoria_prod',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
