# Generated by Django 5.0.6 on 2024-05-26 00:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appModelosDB', '0002_alter_categoriaproducto_nombre_categoria_prod'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='categoria_original',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos_originales', to='appModelosDB.categoriaproducto'),
        ),
        migrations.AddField(
            model_name='producto',
            name='en_promocion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='producto',
            name='lanzamiento_reciente',
            field=models.BooleanField(default=False),
        ),
    ]
