# Generated by Django 5.0.6 on 2024-05-26 02:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appModelosDB', '0003_producto_categoria_original_producto_en_promocion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria_producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appModelosDB.categoriaproducto'),
        ),
    ]
