# Generated by Django 5.0.6 on 2024-05-26 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appModelosDB', '0004_alter_producto_categoria_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='precio_original',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='promocion',
            name='descuento_porcentaje',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
