# Generated by Django 5.0.6 on 2024-05-26 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appModelosDB', '0005_producto_precio_original_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocion',
            name='descuento_porcentaje',
            field=models.IntegerField(default=0),
        ),
    ]
