# Generated by Django 5.0.6 on 2024-05-26 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appModelosDB', '0006_alter_promocion_descuento_porcentaje'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocion',
            name='estado',
            field=models.CharField(default='activo', max_length=50),
        ),
    ]
